/**
 * Emits the design tokens as CSS custom properties for the web app.
 *
 * The important part is the surface-scoped semantic block. Rather than relying on every
 * author to remember that gold changes on light backgrounds, a section declares
 * `.surface-light` or `.surface-dark` and *every* semantic var inside it — including
 * `--color-accent` — resolves correctly. The accessible-gold rule becomes structural
 * instead of a convention people have to remember.
 */

import { palette, derived, dark, light, type SemanticColors } from "./color.ts";
import { fontStack, fontSize, fontWeight, lineHeight, letterSpacing, fluidSize } from "./typography.ts";
import { space, radius, layout, minTouchTarget } from "./space.ts";
import { duration, cssEasing } from "./motion.ts";

function semanticBlock(colors: SemanticColors, indent = "  "): string {
  return Object.entries(colors)
    .map(([key, value]) => `${indent}--color-${kebab(key)}: ${value};`)
    .join("\n");
}

function kebab(s: string): string {
  return s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

export function tokensCss(): string {
  const paletteVars = Object.entries({ ...palette, ...derived })
    .map(([key, value]) => `  --palette-${kebab(key)}: ${value};`)
    .join("\n");

  const spaceVars = Object.entries(space)
    .map(([key, value]) => `  --space-${key}: ${value}px;`)
    .join("\n");

  const radiusVars = Object.entries(radius)
    .map(([key, value]) => `  --radius-${key}: ${value}px;`)
    .join("\n");

  const sizeVars = Object.entries(fontSize)
    .map(([key, value]) => `  --font-size-${kebab(key)}: ${value}px;`)
    .join("\n");

  const weightVars = Object.entries(fontWeight)
    .map(([key, value]) => `  --font-weight-${key}: ${value};`)
    .join("\n");

  const leadingVars = Object.entries(lineHeight)
    .map(([key, value]) => `  --leading-${key}: ${value};`)
    .join("\n");

  const trackingVars = Object.entries(letterSpacing)
    .map(([key, value]) => `  --tracking-${key}: ${value};`)
    .join("\n");

  const durationVars = Object.entries(duration)
    .map(([key, value]) => `  --duration-${key}: ${value}ms;`)
    .join("\n");

  return `/* Generated by @xoholy/design. Do not edit by hand — edit packages/design/src and rebuild. */

:root {
  /* Raw palette — prefer the semantic tokens below in component code. */
${paletteVars}

  /* Type */
  --font-display: ${fontStack.display};
  --font-ui: ${fontStack.ui};
${sizeVars}
${weightVars}
${leadingVars}
${trackingVars}

  /* Fluid display sizes for the marketing site */
  --font-size-hero-fluid: ${fluidSize(44, fontSize.display1)};
  --font-size-display-fluid: ${fluidSize(34, fontSize.display2)};
  --font-size-display-sm-fluid: ${fluidSize(26, fontSize.display3)};

  /* Space & layout */
${spaceVars}
${radiusVars}
  --layout-max-width: ${layout.maxWidth}px;
  --layout-prose-width: ${layout.proseWidth}px;
  --layout-gutter: ${layout.gutter}px;
  --min-touch-target: ${minTouchTarget}px;

  /* Motion */
${durationVars}
  --ease-standard: ${cssEasing("standard")};
  --ease-enter: ${cssEasing("enter")};
  --ease-exit: ${cssEasing("exit")};
  --ease-emphasis: ${cssEasing("emphasis")};
}

/*
 * Surface scopes. Applying one of these sets every semantic color for its subtree,
 * which is how the accessible gold gets chosen mechanically rather than by memory:
 * .surface-dark resolves --color-accent to the brand gold, .surface-light resolves it
 * to the darkened gold that clears WCAG AA on bone.
 */
:root,
.surface-dark {
  color-scheme: dark;
${semanticBlock(dark)}
}

.surface-light {
  color-scheme: light;
${semanticBlock(light)}
}

body {
  background: var(--color-bg);
  color: var(--color-text);
  font-family: var(--font-ui);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

@media (prefers-reduced-motion: reduce) {
  *,
  *::before,
  *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}
`;
}
